config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/today')

  get '/today', to: 'days#today'

  get '/tasks', to: 'tasks#index'

  resources :days, only: %i[index show edit update] do
    resources :tasks, except: %i[index show] do
      member do
        patch 'cancel'
      end
    end
  end

  resources :habits

  patch 'habit_item', to: 'habit_items#update'

  resources :quotes, except: %i[show]

  resources :notes

  devise_for :users
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_rich_text :content

  def self.default_scope
    order(:order, :created_at)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[show edit update destroy]

  def index
    @notes = Note.all.select(:id, :name)
    @note = params[:id] ? Note.find(params[:id]) : Note.order(:order, :created_at).first
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id

    respond_to do |format|
      if @note.save!
        format.turbo_stream
      else
        render :new, status: :unprocessable_entity, notice: 'Something went wrong'
      end
    end
  end

  def show; end

  def edit; end

  def update
    respond_to do |format|
      if @note.update!(note_params)
        format.turbo_stream
      else
        render :edit, status: :unprocessable_entity, notice: 'Something went wrong'
      end
    end
  end

  def destroy
    @note.destroy
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:name, :content, :order)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= turbo_frame_tag "note" do %>
  <%= form_with model: note do |form| %>
    <p>
      <%= form.label :name %>
      <%= form.text_field :name, autocomplete: 'off' %>
    </p>
    <br>
    <p>
      <%= form.rich_text_area :content %>
    </p>
    <p>
      <%= form.submit id: "submit-btn" %>
    </p>
  <% end %>
<% end %>

<% if false %>
  <%= form_with id: 'task-form',
                class: "task-form",
                model: [project, task],
                data: { 
                  controller: "task",
                  action: "turbo:submit-end->task#resetContent",
                  prev_date: str_date(task.target_date),
                  prev_content: task.content,
                  current_date: str_date(task.target_date),
                  current_content: task.content
                } do |form| %>
  <% end %>
<% end %>

app/views/notes/_note.html.erb
<%= turbo_frame_tag "note" do %>
  <%= note.name %>
  <br>
  <br>
  <%= note.content %>
  <br>
  <%= button_to edit_note_path(@note), method: :get do %>
    <%= bootstrap_icon "pencil-square" %>
  <% end %>
  <br>
  <%= button_to note_path(@note),
                method: :delete,
                form: { data: { turbo_confirm: "Are you sure?" } } do %>
    <%= bootstrap_icon "trash3-fill" %>
  <% end %>
<% end %>

app/views/notes/_note_list_item.html.erb
<%= turbo_frame_tag note do %>
  <li>
    <%= link_to note.name, note, data: { turbo_frame: :note } %>
  </li>
<% end %>

app/views/notes/create.turbo_stream.erb
<%= turbo_stream.replace "note", @note %>
<%= turbo_stream.append "notes", partial: "note_list_item", locals: { note: @note } %>
<%= render_random_quote %>

app/views/notes/destroy.turbo_stream.erb
<%= turbo_stream.remove @note %>
<%= turbo_stream.update "note", current_user.notes.first %>

app/views/notes/edit.html.erb
<div class="container">
  <h1>Edit note</h1>
  <%= render "form", note: @note %>
</div>

app/views/notes/index.html.erb
<div class="container notes">
  <div>
    <ul>
      <%= turbo_frame_tag "notes" do %>
        <%= render partial: 'note_list_item', collection: @notes, as: :note %>
      <% end %>
    </ul>
    <br>
    <%= link_to 'Add new note', new_note_path, data: { turbo_frame: :note } %>
    <br>
  </div>

  <div class="note">
    <% if @note %>
      <%= render @note %>
    <% end %>
  </div>
</div>

app/views/notes/new.html.erb
<div class="container">
  <h1>New note</h1>
  <%= render "form", note: @note %>
</div>

app/views/notes/show.html.erb
<div class="container">
  <%= render @note %>
  <%= link_to "back", :back%>
</div>

app/views/notes/update.turbo_stream.erb
<%= turbo_stream.replace "note", @note %>
<%= turbo_stream.update @note, partial: "note_list_item", locals: { note: @note } %>
<%= render_random_quote %>

<%# moze tak jak było tyko że dać "note_#{@note.id}" %>