config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/today')

  get '/today', to: 'days#today'

  get '/tasks', to: 'tasks#index'

  resources :days, only: %i[index show edit update] do
    resources :tasks, except: %i[index show] do
      member do
        patch 'cancel'
      end
    end
  end

  resources :habits

  patch 'habit_item', to: 'habit_items#update'

  resources :quotes, except: %i[show]

  resources :notes

  devise_for :users
end

app/models/day.rb
class Day < ApplicationRecord
  extend FriendlyId
  belongs_to :user, dependent: :destroy
  has_many :tasks, foreign_key: :date, primary_key: :date
  has_many :habits, class_name: 'HabitItem', foreign_key: :date, primary_key: :date
  has_rich_text :summary
  friendly_id :date, use: :slugged

  def self.default_scope
    order(:date)
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, except: %i[index]
  before_action :set_tasks, except: %i[index edit update]
  before_action :set_habits, except: %i[index edit update]
  before_action :set_day_values, only: %i[show today]

  def show; end

  def edit; end

  def update
    respond_to do |format|
      if @day.update!(params.require(:day).permit(:summary))
        format.turbo_stream
        format.html { redirect_to @day }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def today
    @overdue_tasks = current_user.tasks.includes(:day).not_completed

    render :show
  end

  private

  def set_day
    @day = if params[:action] == 'today'
             current_user.days.preload(:tasks, :habits).find_by_date(Date.today)
           else
             current_user.days.preload(:tasks, :habits).friendly.find(params[:id])
           end
  end

  def set_tasks
    @tasks = @day.tasks
  end

  def set_habits
    day_habits = Habit.find_by_sql(['
      SELECT
        id,
        item_id,
        name,
        date,
        quantity,
        daily_target
      FROM
        habits
      LEFT OUTER JOIN (
        SELECT
          date,
          quantity,
          id as item_id,
          habit_id
        FROM
          habit_items
        WHERE
          date = ?
      ) as habit_items ON
        habits.id = habit_items.habit_id
      WHERE ? = ANY(habits.frequency)
      ORDER BY habits.order
    ', @day.date, @day.date.wday])

    @monitored = []
    @habits = []
    @total_habits = 0
    @completed_habits = 0

    day_habits.map do |habit|
      habit.quantity = habit.quantity.to_i # 0 if habit_item doesn't exist
      habit.date = @day.date
      if habit.daily_target > 0
        @habits << habit
        @total_habits += habit.daily_target
        @completed_habits += habit.quantity <= habit.daily_target ? habit.quantity : habit.daily_target
      else
        @monitored << habit
      end
    end
  end

  def set_day_values
    if @day.date <= Date.today
      session[:day_values] = {
        'total_tasks' => @day.total_tasks,
        'completed_tasks' => @day.completed_tasks,
        'completed_habits' => @completed_habits,
        'total_habits' => @total_habits
      }
    end
  end
end

app/helpers/days_helper.rb
module DaysHelper
  def day_title(date)
    date.strftime('%A %-d %B')
  end

  def day_habit_css_class(habit)
    return 'success' if habit.quantity >= habit.daily_target
    return 'fail' if habit.quantity < habit.daily_target && habit.date < today
  end
end

app/views/days/_day_summary.html.erb
<%= turbo_frame_tag "day-summary", 
                    class: "day__summary",
                    data: { controller: "base", action: "turbo:frame-render->base#scrollToBottom" } do %>
  <h2>Summary</h2>
  <%= day.summary %>
  <%= link_to (@day.summary.body ? 'Edit' : 'Add') + ' summary', edit_day_path(day.date) %>
<% end %>

app/views/days/_habit_task.html.erb
<%= turbo_frame_tag "task_habit_#{habit.id}" do %>
  <div class="task task-habit <%= day_habit_css_class(habit) if habit.daily_target > 0 %><%= ' inactive' if habit.date != today %>">
    <%= button_to habit_item_path({
                                    habit_id: habit.id,
                                    date: habit.date,
                                    type: (habit.quantity >= habit.daily_target ? 'decrement' : 'increment'),
                                    view: 'day'
                                  }),
                                  class: "task__content",
                                  disabled: habit.date != today,
                                  method: :patch do %>
      <%= bootstrap_icon ((habit.date < today && habit.quantity < habit.daily_target) ? "x-square-fill" : habit.quantity >= habit.daily_target ? "check-square-fill" : "square") %>
      <%= habit.name %>

      <% if habit.daily_target > 1 %>
        <%= habit.quantity %>/<%= habit.daily_target %>
        <% if habit.quantity > 0 && habit.quantity < habit.daily_target && habit.date == today %>
          <span class="progress" style="height: <%= 14 * (habit.quantity / habit.daily_target.to_f ) %>px"></span>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/days/_monitored_task.html.erb
<%= turbo_frame_tag "task_monitored_#{habit.id}" do %>
  <div class="task task-monitored<%= ' inactive' if habit.date != today %>">
    <%= button_to habit_item_path({
                                    habit_id: habit.id,
                                    date: habit.date,
                                    type: 'increment',
                                    view: 'day'
                                  }),
                                  disabled: habit.date != today,
                                  class: "task__content",
                                  method: :patch do %>
      <%= bootstrap_icon "plus-square" %>
      <%= habit.name %>
      <% if habit.date <= today %>
        - <%= pluralize(habit.quantity, 'time') %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/days/edit.html.erb
<%= turbo_frame_tag "day-summary" do %>
  <%= form_with model: @day do |form| %>
    <div class="field">
      <%= form.rich_text_area :summary %>
      <%= form.submit %>
    </div>
  <% end %>
  <%= link_to 'Back', :back %>
<% end %>

app/views/days/index.html.erb
<div class="container">
  <h1>All days</h1>
  <%= session[:day_values] %>
  <% @days.each do |day| %>
    <%= day.date %>
    <br>
  <% end %>
</div>

app/views/days/show.html.erb
<div class="container day">
  <div class="day__header">
    <%= link_to '<', day_path(@day.date - 1.day) %>
    <h1>
      <%= day_title @day.date %>

      <%= turbo_frame_tag "#{today}-percentage" do %>
        <% if @day.date <= today && (@day.total_tasks + @habits.size ) > 0 %>
          <%= day_percentage %>
        <% end %>
      <% end %>
    </h1>
    <%= link_to '>', day_path(@day.date + 1.day) %>
  </div>

  <% if @habits.any? %>
    <div class="day__habits">
      <h2>Habits</h2>
      <%= render partial: 'habit_task', collection: @habits, as: :habit %>
    </div>
  <% end %>

  <div class="day__tasks">
    <% if @overdue_tasks && @overdue_tasks.any? %>
      <div>
        <h2>Overdue tasks</h2>
        <%= render partial: 'tasks/task_overdue', collection: @overdue_tasks, as: :task %>
      </div>
    <% end %>

    <%= turbo_frame_tag "tasks_#{@day.date}" do %>
      <h2>Tasks</h2>

      <%= render @tasks %>
    <% end %>

    <% if @day.date >= today %>
      <%= turbo_frame_tag Task.new do %>
        <%= link_to "Add new task", new_day_task_path(@day) %>
      <% end %>
    <% end %>
  </div>

  <% if @monitored.any? %>
    <div class="day__monitored">
      <h2>Monitored</h2>

      <%= render partial: 'monitored_task', collection: @monitored, as: :habit %>
    </div>
  <% end %>

  <%= render "day_summary", day: @day %>
</div>

app/views/days/update.turbo_stream.erb
<%= turbo_stream.replace "day-summary", partial: 'days/day_summary', locals: { day: @day } %>