config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/today')

  get '/today', to: 'days#today'

  get '/tasks', to: 'tasks#index'

  resources :days, only: %i[index show edit update] do
    resources :tasks, except: %i[index show] do
      member do
        patch 'cancel'
      end
    end
  end

  resources :habits

  patch 'habit_item', to: 'habit_items#update'

  resources :quotes, except: %i[show]

  resources :notes

  devise_for :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include ApplicationHelper

  def authorize_user(user_id)
    redirect_to root_path unless current_user.id == user_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_random_quote
    notice = Quote.order('RANDOM()').first

    if notice
      flash.now[:notice] = notice.content
      turbo_stream.prepend 'flash', partial: 'flash'
    end
  end

  def param_date
    return params[:date].to_date if params[:date]
    return params[:day_date].to_date if params[:day_date]

    Date.today
  end

  def today
    Date.today
  end

  def day_percentage
    percentage(
      session[:day_values]['total_tasks'],
      session[:day_values]['completed_tasks'],
      session[:day_values]['total_habits'],
      session[:day_values]['completed_habits']
    )
  end

  def habit_day_percentage(total_tasks, completed_tasks, total_habits, completed_habits)
    total_habits ||= 0 # because of day model includes total_tasks and completed_tasks
    completed_habits ||= 0

    return '-' if [completed_tasks, completed_habits, total_tasks, total_habits].all?(0)

    percentage(total_tasks, completed_tasks, total_habits, completed_habits)
  end

  private

  def percentage(total_tasks, completed_tasks, total_habits, completed_habits)
    total = total_tasks + total_habits
    completed = completed_tasks + completed_habits
    completion = (completed / total.to_f) * 100

    (completion == completion.round ? completion.round : completion.round(1)).to_s + '%'
  end
end

app/views/application/_flash.html.erb
<%= turbo_frame_tag 'flash' do %>
  <% flash.each do |flash_type, message| %>
    <div id="flash" class="flash">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/application/_menu.html.erb
<nav id="menu" class="menu">
  <button class="menu-btn"
          data-controller="base"
          data-action="click->base#toggleMenu">
    <%= bootstrap_icon "menu-button-wide", color: "white" %>
  </button>
  <ul>
    <li>
      <%= link_to "Today", today_path %>
    </li>
    <li>
      <%= link_to "Upcoming", tasks_path %>
    </li>
    <li>
      <%= link_to "Habits", habits_path %>
    </li>
    <li>
      <%= link_to "Notes", notes_path %>
    </li>
    <li>
      <%= link_to "Quotes", quotes_path %>
    </li>
  </ul>
  <button class="theme-btn"
          data-controller="base"
          data-action="click->base#toggleTheme">
    Toggle theme
  </button>
</nav>