config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/today')

  get '/today', to: 'days#today'

  get '/tasks', to: 'tasks#index'

  resources :days, only: %i[index show edit update] do
    resources :tasks, except: %i[index show] do
      member do
        patch 'cancel'
      end
    end
  end

  resources :habits

  patch 'habit_item', to: 'habit_items#update'

  resources :quotes, except: %i[show]

  resources :notes

  devise_for :users
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user
  has_many :items, class_name: 'HabitItem' # delete items but only where date >= today
  validates :name, presence: true, length: { minimum: 2 }

  def self.default_scope
    order(:order)
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  include HabitsHelper

  def index
    @start_date = params[:view] ? param_date.beginning_of_week : param_date.beginning_of_month
    @end_date = params[:view] ? @start_date.end_of_week : @start_date.end_of_month
    @end_date = today if @start_date == today.beginning_of_month
    @days_of_month = params[:view] ? @start_date..@end_date : @start_date..@start_date.end_of_month

    habits = current_user.habits.order(:created_at).all
    habits_with_items = current_user.habits
                                    .order(:created_at)
                                    .eager_load(:items)
                                    .where('date >= ? AND date <= ?', @start_date, @end_date)

    @habits = []
    @monitored = []

    habits.each do |habit|
      habit_with_items = habits_with_items.find { |h| h.id = habit.id }

      habit.items + habit_with_items.items if habit_with_items

      if habit.daily_target > 0
        @habits << habit
      else
        @monitored << habit
      end
    end

    @days = Day.find_by_sql(["
      SELECT
        days.date,
        days.total_tasks,
        days.completed_tasks,
        SUM(
          CASE WHEN habits.quantity > habits.daily_target THEN habits.daily_target ELSE habits.quantity END
        ) as completed_habits,
        SUM(habits.daily_target) as total_habits
      FROM
        days
        LEFT OUTER JOIN (
          SELECT
            date,
            quantity,
            daily_target
          FROM
            habit_items
            JOIN habits ON habit_items.habit_id = habits.id
          WHERE
            habits.daily_target > 0
        ) as habits ON days.date = habits.date
      WHERE
        days.date >= ?
        AND days.date <= ?
      GROUP BY
        days.date,
        days.total_tasks,
        days.completed_tasks
      ORDER BY
        days.date
    ", @start_date, @end_date])

    # @days = current_user.days.where('date >= ? AND date <= ?', @start_date, today)
    # @habits_dates = {}
    # @days.each do |day|
    #   date = {
    #     total: 0,
    #     completed: 0
    #   }

    #   @habits.map do |habit|
    #     next unless habit.daily_target > 0

    #     daily_target = habit.daily_target
    #     habit_item = habit.items.find { |item| item.date == day.date }

    #     if habit_item
    #       date[:total] += daily_target
    #       date[:completed] += habit_item.quantity <= daily_target ? habit_item.quantity : daily_target
    #     end
    #   end

    #   @habits_dates[day.date.to_s] = date
    # end
  end

  def show
    @habit = Habit.find(params[:id])
  end

  def new
    @habit = Habit.new
  end

  def create
    @habit = Habit.new(habit_params)
    @habit.frequency = habit_frequency

    @habit.user_id = current_user.id

    respond_to do |format|
      if @habit.save
        format.turbo_stream
        format.html { redirect_to habits_path }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @habit = Habit.find(params[:id])

    authorize_user(@habit.user_id)
  end

  def update
    @habit = Habit.find(params[:id])
    @habit.frequency = habit_frequency

    respond_to do |format|
      if @habit.update!(habit_params)
        format.html { redirect_to habits_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @habit = Habit.find(params[:id])
    @habit.destroy

    redirect_to habits_path
  end

  private

  def habit_params
    params.require(:habit).permit(:name, :daily_target, :weekly_target, :status, :frequency, :order)
  end
end

app/helpers/habits_helper.rb
module HabitsHelper
  def habit_frequency
    params[:habit][:frequency].reject(&:blank?).map(&:to_i)
  end
end

app/views/habits/_form.html.erb
<%= turbo_frame_tag habit do %>
  <%= form_with model: habit do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name, autofocus: true %>
    </p>
    <p>
      <%= form.label :daily_target %><br>
      <%= form.number_field :daily_target %>
    </p>
    <p>
      <%= form.label :weekly_target %><br>
      <%= form.number_field :weekly_target %>
    </p>
    <p>
      <%= form.collection_check_boxes(:frequency,
                                      { 'Mon': 1, 'Tue': 2, 'Wed': 3, 'Thu': 4, 'Fri': 5, 'Sat': 6, 'Sun': 0 },
                                      :last,
                                      :first) %>
    </p>
    <p>
      <%= form.label :order %><br>
      <%= form.number_field :order %>
    </p>
    <p>
      <%= form.submit data: { turbo_frame: "_top"} %>
    </p>
  <% end %>
  <%= link_to 'Back', :back, data: { turbo_frame: "_top"} %>
<% end %>

app/views/habits/_habit.html.erb
<%= turbo_frame_tag habit do %>
  <div class="row">
    <div class="cell">
      <%= link_to habit.name, edit_habit_path(habit), data: { turbo_frame: "_top" } %>
    </div>
    <% (start_date..end_date).each do |date| %>
      <%= render 'habit_items/habit_item',
                  habit_item: habit.items.detect{|h| h.date == date},
                  target: (habit.daily_target if habit.frequency.include?(date.wday)),
                  habit_id: habit.id,
                  date: %>
    <% end %>
  </div>
<% end %>

app/views/habits/_habit_item.html.erb
<div class="cell <%= habit_item_css_class(target, habit_item) %>">
  <% if habit_item %>
    <%= button_to '+', habit_habit_item_path(habit_item.habit_id, habit_item, habit_item: { quantity: habit_item.quantity + 1 }), method: :patch %>
    <%= habit_item.quantity %>
    <%= button_to '-', habit_habit_item_path(habit_item.habit_id, habit_item, habit_item: { quantity: habit_item.quantity - 1 }), method: :patch %>
  <% end %>
</div>

app/views/habits/create.turbo_stream.erb
<%= turbo_stream.update Habit.new, partial: 'habits/form', locals: { habit: Habit.new } %>

<%= turbo_stream.append "monitored", partial: 'habits/habit', locals: { habit: @habit, start_date: today.beginning_of_month, end_date: today } %>

app/views/habits/edit.html.erb
<div class="container">
  <h1>Edit habit</h1>

  <%= turbo_frame_tag @habit do %>
    <%= render 'form', habit: @habit %>
  <% end %>
  <br>
  <%= button_to 'Delete', habit_path(@habit), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } %>
</div>

app/views/habits/index.html.erb
<div class="habits">

  <div class="actions">
    <% if param_date.beginning_of_month > current_user.created_at.beginning_of_month || (params[:view] == 'week' && param_date.beginning_of_week > current_user.created_at.beginning_of_week) %>
      <%= link_to 'prev', habits_path({ date: param_date - (params[:view] ? 1.week : 1.month), view: params[:view] }) %>
    <% end %>

    <%= link_to 'month', habits_path(), class: ('active' if params[:view].nil?) %>
    <%= link_to 'week',  habits_path({ date: param_date.beginning_of_week, view: 'week' }), class: ('active' if params[:view] == 'week') %>

    <% if param_date.end_of_week < today || (params[:view] == 'week' && param_date.end_of_week < today) %>
      <%= link_to 'next', habits_path({ date: param_date + (params[:view] ? 1.week : 1.month), view: params[:view] }) %>
    <% end %>
  </div>

  <div class="table">
    <div class="row days">
      <div class="cell">
        <%= link_to 'Add new habit', new_habit_path %>
      </div>
      <% @days_of_month.each do |day| %>
        <div class="cell">

          <%= day.strftime('%-d') %>

          <small>
            <%= day.strftime('%a') %>
          </small>
        </div>
      <% end %>
    </div>

    <%= turbo_frame_tag "habits" do %>
      <% @habits.each do |habit|%>
        <%= render habit, start_date: @start_date, end_date: @end_date %>
      <% end %>
    <% end %>

    <%= turbo_frame_tag "monitored" do %>
      <% @monitored.each do |habit|%>
        <%= render habit, start_date: @start_date, end_date: @end_date %>
      <% end %>
    <% end %>

    <%= turbo_frame_tag "days" do %>
      <div class="row">
        <div class="cell">
          Day %
        </div>
        <% @days.each do |day| %>
          <%= turbo_frame_tag "#{day.date}-percentage", class: "cell" do %>
            <%= habit_day_percentage(day.total_tasks,
                                   day.completed_tasks,
                                   day.total_habits,
                                   day.completed_habits) %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/habits/new.html.erb
<div class="container">
  <h1>New habit</h1>

  <%= render 'form', habit: @habit %>
</div>

app/views/habits/show.html.erb
<h1>
  <%= @habit.name %>
</h1>
<%= link_to 'back', :back %>